### ISSUE TITLE
Why is the FarmingSkill mod deprecated

### ISSUE THREAD

**Issue by Kogs** [tpill90/ValheimMods#2]
Hi, I just was wondering why the FarmingSkill mod is deprecated?

**Comment by tpill90** [comment]
My mod is completely superceded by Smoothbrains mod : https://valheim.thunderstore.io/package/Smoothbrain/Farming/

I decided to deprecate it since his mod actually combines the three farming mods I was using. I'll update my mod readme to point to his mod instead
